name: CICD build push docker image
on:
 push:

jobs:
  build:
   runs-on: ubuntu-latest 
   steps:
     - name: checkout repositoy 
       uses: actions/checkout@v2 
     - name: docker login
       uses: docker/login-action@v3
       with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
     - name: build docker images 
       run: docker build -t my-app .
     - name: tag
       run: docker tag betrand1997 my-app:latest
     - name: push image
       run: docker push betrand1997/my-app:latest
     - name: run image
       run: docker run -d -p 8080:80 my-app --name my-container
      

