name: BUILD PUSH DOCKER IMAGE
on: 
 push:
   branches:
     - dev 

jobs:
  build: 
   if: true
   runs-on: ubuntu-latest 

   steps:
     - name: checkout action
       uses: actions/checkout@v2 
     - name: login to docker 
       uses: docker/login-action@v3
       with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: build with docker 
       run: docker build -t app . 
     - name: run the app 
       run: |
        docker run -d -p 6061:80 app --name my-container
        docker images 
        docker ps 
     - name: tag 
       run: docker tag app:latest betrand1997/app:latest
     - name: push image 
       run: docker push betrand1997/app:latest
