name: Deploy app to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}
          resource-group: my-resource-group
          cluster-name: my-aks-cluster

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./kubernetes/namespace.yaml
          kubectl get ns
          kubectl apply -f ./kubernetes/Deployment.yaml
          kubectl apply -f ./kubernetes/service.yaml
