name: Deploy app to Azure
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest 
   steps:
     - name: checkout repo 
       uses: actions/checkout@v2 
     - name: login to azure 
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: my-resource-group
        cluster-name: my-aks-cluster
     - name: set aks
       uses: azure/aks-set-context@v1  
     - name: deploy to aks 
       run: |
        kubectl create -f ./kubernetes/namespace.yaml
        kubectl create -f ./kubernetes/deployment.yaml
        kubectl create -f ./kubernetes/service.yaml
        

        

      
       
          
   
       
         
        